version: 2
jobs:
  prepare1:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: mkdir prepare1 
      - run: touch prepare1/prepare1.txt
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./prepare1
  prepare2:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: mkdir prepare2
      - run: touch prepare2/prepare2.txt
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./prepare2
  test:
    docker:
      - image: circleci/node
    # working_directory: *prepare_workspace
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: ls ./ 
workflows:
  version: 2
  build:
    jobs: # prepare1, prepare2 -> testの順に行う
      - prepare1
      - prepare2
      - test:
          requires:
            - prepare1
            - prepare2
