version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install # インストール処理
      - persist_to_workspace:
          root: ~/project
          paths: # 保持したいパスを指定
            - ./node_modules 
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn test # テストコマンド実行
  lint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint # テストコマンド実行
workflows:
  version: 2
  build:
    jobs: # prepare -> testの順に行う
      - prepare
      - test:
          requires:
            - prepare
      - lint:
          requires:
            - prepare
