version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - ./node_modules
      - run: yarn install
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: yarn mocha
workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare
      - test
