version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node
    working_directory: ~/project
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./node_modules
      - run: yarn install
  test:
    docker:
      - image: circleci/node
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn mocha
workflows:
  version: 2
  build:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
