aliasis:
  - &prepare_workspace
      /tmp/prepare
version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node
    working_directory: *prepare_workspace
    steps:
      - checkout
      - run: yarn install # インストール処理
      - persist_to_workspace:
          root: *prepare_workspace
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node
    # working_directory: *prepare_workspace
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn test # テストコマンド実行
workflows:
  version: 2
  build:
    jobs: # prepare -> testの順に行う
      - prepare
      - test:
          requires:
            - prepare
